#!/bin/sh
# postrm script for orix
# Cleanup after package removal

set -e

case "$1" in
    purge)
        rm -rf /var/cache/orix
        rm -rf /var/log/orix
        ;;
    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;
    *)
        echo "postrm called with unknown argument '$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#
