#!/bin/sh
# prerm script for orix
# Cleanup on removal

set -e

case "$1" in
    remove|upgrade|deconfigure)
        # Nothing to clean up - orix stores data in ~/.orix
        ;;
    failed-upgrade)
        ;;
    remove)
        ;;
    *)
        echo "prerm called with unknown argument '$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#
